server:
  port: 8090

spring:
  application:
    name: edu-config-boot
  cloud:
    config:
      server:
        git:
          uri: https://github.com/suikataro/learning-edu-repo.git
          username: suikataro
          password: 58837Yundi**
          default-label: main